[sections.blog]
plugin = "feed"
url = "https://kuberwastaken.github.io/blog/index.xml"  # Replace with your feed.
skip = 1  # Skip the first entry in the feed

[sections.last_updated]
plugin = "current_date"
inline = true